version: 2.1

commands:
  install_and_test:
    parameters:
      composer_flags:
        type: string
        default: ""
      laravel:
        type: string
        default: ""
    steps:
      - checkout
      - run: echo 'export APP_ENV="test"' >> $BASH_ENV
      - run: composer self-update
      - run: composer require "laravel/framework=<< parameters.laravel >>" --prefer-source --no-interaction --no-suggest
      - run: COMPOSER_DISCARD_CHANGES=true composer update << parameters.composer_flags >> --no-interaction --prefer-source
      - run: vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - php73-laravel60
      - php73-laravel60-prefer-lowest

jobs:
  php73-laravel60-prefer-lowest:
    docker:
      - image: circleci/php:7.3
    steps:
      - install_and_test:
          laravel: ^6.0
          composer_flags: --prefer-lowest
  php73-laravel60:
    docker:
      - image: circleci/php:7.3
    steps:
      - install_and_test:
          laravel: ^6.0
